server:
  port: 8080

logging:
  level:
    "liquibase" : info
sentry:
  dsn: https://7a9a348dbfaf484a802e9312282d46ff@o1233380.ingest.sentry.io/6382166
  traces-sample-rate: 1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_website
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      platform: postgres
  jpa:
    show-sql: true
    generate-ddl: false